---
title: Whats Up Hanoi
timezone: Asia/Bangkok
collections:
  eventstonight:
    title: Events tonight
    output: false
  ourevents:
    title: Our events
    output: false
  posts:
    title: Posts
    output: true
  promotions:
    title: Promotions
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: eventstonight
  values:
    Viet title: 
    Event date: 2017-06-21 14:00:00.000000000 Z
    Venue: Please enter
    Event URL: https://www.facebook.com/events/
- scope:
    path: ''
    type: promotions
  values:
    Event date: 2017-06-21 14:00:00.000000000 Z
    Venue: 
    From date: 2017-06-23 05:00:00.000000000 Z
    To date: 2017-06-24 05:00:00.000000000 Z
    Is on top: false
    Link: 
    Feature type: 
    Heading: 
    Image: 
    Color: 
encoding: utf-8
lang: en
description: Events in Hanoi today.
baseurl: 
url: www.whatsuphanoi.com
author: Whats Up Hanoi
logo: "/assets/images/sociallogo.png"
image: "/assets/images/socialimage.png"
social:
  name: Whats Up Hanoi
  links: https://www.facebook.com/whatsuphanoievents
livereload: true
mailchimp: true
followus: true
markdown: kramdown
permalink: pretty
sass:
  sass_dir: assets/_stylesheets/
gems:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-autoprefixer
exclude:
- Gemfile
- Gemfile.lock
