---
title: Whats Up Hanoi
timezone: Asia/Bangkok
collections:
  eventstonight:
    title: Events tonight
    output: false
  ourevents:
    title: Our events
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: ourevents
  values:
    Event date: 2017-06-21 21:00:00 +07:00
    Venue: Please enter
    Event URL: https://www.facebook.com/events/
- scope:
    path: ''
    type: eventstonight
  values:
    Viet title: 
    Event date: 2017-06-21 21:00:00 +07:00
    Venue: Please enter
    Event URL: https://www.facebook.com/events/
encoding: utf-8
lang: en
description: Events in Hanoi today.
baseurl:
url: www.whatsuphanoi.com
author: Whats Up Hanoi
logo: "/assets/images/sociallogo.png"
image: "/assets/images/socialimage.png"
social:
  name: Whats Up Hanoi
  links: https://www.facebook.com/whatsuphanoievents
livereload: true
markdown: kramdown
permalink: pretty
sass:
  sass_dir: assets/_stylesheets/
gems:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-autoprefixer
exclude:
- Gemfile
- Gemfile.lock
