---
title: Whats Up Hanoi !?
timezone: Asia/Bangkok
collections:
  eventstonight:
    title: Events tonight
    output: false
    Genres:
    - art
    - music
  genres:
    title: Genres
    output: true
  ourevents:
    title: Our events
    output: false
  posts:
    title: Posts
    output: true
  promotions:
    title: Promotions
    output: false
  uploads:
    title: Uploads
    output: true
  scrapers:
    title: Scrapers
    output: false
defaults:
- scope:
    path: ''
    type: scrapers
  values:
    Event date:
    Venue:
    Event URL:
    Genre:
- scope:
    path: ''
    type: eventstonight
  values:
    Event date: 2017-06-21 14:00:00.000000000 Z
    Venue: Please enter
    Event URL: https://www.facebook.com/events/
    Genre:
- scope:
    path: ''
    type: ourevents
  values:
    Event date: 2017-06-21 14:00:00.000000000 Z
    Venue: Please enter
    Event URL: https://www.facebook.com/events/
- scope:
    path: ''
    type: promotions
  values:
    Event date: 2017-06-21 14:00:00.000000000 Z
    Venue:
    From date: 2017-06-23 05:00:00.000000000 Z
    To date: 2017-06-24 05:00:00.000000000 Z
    Is on top: false
    Link:
    Feature type:
    Heading:
    Image:
    Color:
encoding: utf-8
lang: en
headline: EVENTS | HANOI | TODAY
description: Hand-picked selection of the best events happening in Hanoi today.
baseurl:
url: http://www.whatsuphanoi.com
livereload: true
mailchimp: true
followus: true
markdown: kramdown
permalink: pretty
sass:
  sass_dir: assets/_stylesheets/
  style: compressed
gems:
- jekyll-autoprefixer
exclude:
- Gemfile
- Gemfile.lock
